name: build
on:
  workflow_dispatch:
  push:
    paths:
      - 'Docker/**'
      - '.github/workflows/*'
      
  schedule:
    - cron: '0 0 * * 0'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout FileFlows
        uses: actions/checkout@v3

      - name: Docker meta
        id: docker_meta
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        if: "${{ env.DOCKER_USERNAME != '' }}"
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/fileflows
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            type=schedule,pattern={{date 'YYYYMMDD'}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker
        if: steps.docker_meta.outcome == 'success'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build
        if: steps.docker_meta.outcome == 'skipped'
        uses: docker/build-push-action@v4
        with:
          context: Docker
          platforms: linux/amd64
          file: Docker/Dockerfile.non-free
          push: false
          tags: fileflows:action

      - name: Build and push
        id: docker_build
        if: steps.docker_meta.outcome == 'success'
        uses: docker/build-push-action@v4
        with:
          context: Docker
          platforms: linux/amd64
          file: Docker/Dockerfile.non-free
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Image digest
        if: steps.docker_meta.outcome == 'success'
        run: echo ${{ steps.docker_build.outputs.digest }}
