name: build
on:
  push:
    paths:
      - 'Docker/**'
      
  schedule:
    - cron: '0 0 * * 0'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout FileFlows
        uses: actions/checkout@v3

      - name: Docker meta
        id: docker_meta
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        if: "${{ env.DOCKER_USERNAME != '' }}"
        uses: docker/metadata-action@v4
        with:
          images: docker.luigi311.com/${{ secrets.DOCKER_USERNAME }}/fileflows
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            type=schedule,pattern={{date 'YYYYMMDD'}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        if: steps.docker_meta.outcome == 'success'
        uses: docker/login-action@v1
        with:
          registry: docker.luigi311.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Clear cache on scheduled run
        if: ${{ github.event_name == 'schedule' }}
        run: rm -rf /tmp/.buildx-cache
      
      - name: Build
        if: steps.docker_meta.outcome == 'skipped'
        uses: docker/build-push-action@v2
        with:
          context: Docker
          platforms: linux/amd64
          file: Docker/Dockerfile.non-free
          push: false
          tags: fileflows:action
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Build and push
        id: docker_build
        if: steps.docker_meta.outcome == 'success'
        uses: docker/build-push-action@v2
        with:
          context: Docker
          platforms: linux/amd64
          file: Docker/Dockerfile.non-free
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Image digest
        if: steps.docker_meta.outcome == 'success'
        run: echo ${{ steps.docker_build.outputs.digest }}
